### PR TITLE
add function to send password reset email

### PR DESCRIPTION
**Pull request by jiachengzhang1**
## Why ##
User can reset password

## What Changed ##
Add event handler for Reset Password button on the profile setting page

## How I Tested ##
Add the following to the `.env` file for testing
```
REACT_APP_ENV=development
REACT_APP_TEST_EMAIL=<replace this with your email>
```
On the profile settings page, click reset password, you should be able to get an email, by following the steps, you can change your password.

Note, the above is for testing, for production, create an account with your own emails (not emails from production Firestore) to test this feature to avoid spamming.

## What’s Next ## 
Need a pretty email template, this can be set up through Firebase console.

## Link to Ticket/ Bug ##
https://www.notion.so/icontribute/Reset-Password-Backend-Functionality-4d6af7097b1540a69fb65c48bec16801

### CODE REVIEW

**Review by pharmacist102 — APPROVED** [review]
Reset password functionality works on the Profile Settings Page:
Screen Shot 2021-12-01 at 10 15 28 PM

Questions:
1. Can we implement the same functionality for the Login Page when the user clicked "Forget Password?" If so, how can we ask the user for their email address? Should we use a separate modal to ask for the email address?
Screen Shot 2021-12-01 at 10 23 16 PM

2. Do we need a message on the Login Page saying: "A link has been sent to your email to reset your password."
Screen Shot 2021-12-01 at 10 15 03 PM

**Comment by jiachengzhang1** [comment]
Add the page for forgot password, just click the `Forget password?` link to test it.

**Review by pharmacist102 — APPROVED** [review]
Hey Jiacheng,
Everything seems to be working fine. Can you make it so that the "Reset Password" functionality works without needing the .env file?
I tested resetting my password using the "Forget Password" button on the login screen and the "Reset Password" button on the Profile Setting Page.
- The "Forget Password" button on the login screen works fine.
- The "Reset Password" button on the Profile Setting Page sends the email to the email address listed in the  ".env" file.
Thanks!
- James

**Comment by jiachengzhang1** [comment]
> 

The "reset password" doesn't need the `.env` to work in production, it's to avoid sending spams. Are you saying to show a different view (i.e., ask devs to enter the email) for dev env?

**Comment by jiachengzhang1** [comment]
@pharmacist102  I merged it, if there are any changes needs for the concern above, I'll make a new PR.

**Pull request merged**
