### PR TITLE
add frontend change for delete opportunity

### PR DESCRIPTION
**Pull request by jiachengzhang1**
## Why ##
add frontend change for delete opportunity

## What Changed ##
add frontend change for delete opportunity

## How I Tested ##
n/a

## What’s Next ## 
n/a

## Link to Ticket/ Bug ##
https://www.notion.so/icontribute/Remove-the-event-id-from-organization-s-collection-firebase-wrapper-58c259708ae849ab85e132f36cdbe672

## Screenshot ##
n/a

### CODE REVIEW

**Review by pharmacist102 — APPROVED** [review]
@jiachengzhang1 => Tested deleting an iContribute opportunity after a student has applied to it.
- It looks like the eventID is correctly deleted from the organization's "event" array, but not the student's "event" array. I think this is fine for now because the mobile app handles a "deleted" opportunity by not displaying it in the mobile app.
- However, we might want to consider sending the student a notification when an organization deletes the opportunity. Is this possible using the Firebase-wrapper?

**Comment by jiachengzhang1** [comment]
> 



> @jiachengzhang1 => Tested deleting an iContribute opportunity after a student has applied to it.
> 
> * It looks like the eventID is correctly deleted from the organization's "event" array, but not the student's "event" array. I think this is fine for now because the mobile app handles a "deleted" opportunity by not displaying it in the mobile app.
> * However, we might want to consider sending the student a notification when an organization deletes the opportunity. Is this possible using the Firebase-wrapper?

I got your points, yes, I can add that feature. Should the event be deleted from student's saved event list too?

**Comment by pharmacist102** [comment]
> > 
> 
> > @jiachengzhang1 => Tested deleting an iContribute opportunity after a student has applied to it.
> > 
> > * It looks like the eventID is correctly deleted from the organization's "event" array, but not the student's "event" array. I think this is fine for now because the mobile app handles a "deleted" opportunity by not displaying it in the mobile app.
> > * However, we might want to consider sending the student a notification when an organization deletes the opportunity. Is this possible using the Firebase-wrapper?
> 
> @pharmacist102 I got your points, yes, I can add that feature. Should the event be deleted from student's saved event list too? => Yes, please delete the eventID from the student's saved event list as well.
@jiachengzhang1

**Comment by jiachengzhang1** [comment]
I will implement the change in a new PR

**Pull request merged**
